repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.1
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
- repo: https://github.com/redeboer/taplo-pre-commit
  rev: '0.9.1rc1'
  hooks:
    - id: taplo
- repo: https://github.com/oxipng/oxipng
  rev: v9.1.5
  hooks:
  - id: oxipng
    args: ['--opt=3', '--interlace=0', '--strip=safe']
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.2
  hooks:
  - id: mypy
