repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: double-quote-string-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 21.7b0  # https://github.com/psf/black/releases
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.9.3  # https://github.com/PyCQA/isort/releases
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910  # https://github.com/python/mypy/releases
  hooks:
  - id: mypy
    args: []
    additional_dependencies: [matplotlib, pygraphviz, xdot]
- repo: https://github.com/pycqa/pylint
  rev: v2.10.2  # https://github.com/PyCQA/pylint/releases
  hooks:
  - id: pylint
    additional_dependencies: [matplotlib, pygraphviz, xdot]
