repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: '23.10.0'
  hooks:
  - id: black
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.1
  hooks:
  - id: ruff
    args: [--fix]
- repo: https://github.com/shssoichiro/oxipng
  rev: v9.0.0
  hooks:
  - id: oxipng
    args: ['--opt=3', '--interlace=0', '--strip=safe']
