repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: double-quote-string-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 22.12.0  # https://github.com/psf/black/releases
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: v5.11.3  # https://github.com/PyCQA/isort/releases
  hooks:
  - id: isort
- repo: https://github.com/pycqa/pylint
  rev: v2.15.9  # https://github.com/PyCQA/pylint/releases
  hooks:
  - id: pylint
    args:
    - '--ignored-modules=pygraphviz'
    additional_dependencies: [get_version, xdot, matplotlib]
