[project]
name = 'gvrender'
authors = [{ name = 'Phil A.', email = 'flying-sheep@web.de' }]
readme = 'README.rst'
classifiers = [
    'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Programming Language :: Python :: 3',
]
dynamic = ['version', 'description']
requires-python = '>=3.8'
dependencies = [
    'get_version',
    'PyGraphviz',
    'matplotlib',
]

[project.optional-dependencies]
test = [
    'pytest',
]

[project.urls]
# Documentation = 'https://gvrender.readthedocs.org/en/latest/'
Source = 'https://github.com/flying-sheep/gvrender'

[tool.black]
line-length = 100
skip-string-normalization = true

[tool.isort]
line_length = 100
profile = 'black'
multi_line_output = 3

[tool.pylint.messages_control]
disable = [
    'import-outside-toplevel',
]
variable-rgx = '([xyijwh]|[^\W\dA-Z][^\WA-Z]{2,}|_[^\WA-Z]*|__[^\WA-Z\d_][^\WA-Z]+__)$'

[tool.pytest.ini_options]
xfail_strict = true

[tool.pyright]
include = ['src']

[tool.maturin]
python-source = 'src/gvrender'

[build-system]
requires = ['maturin>=0.14,<0.15']
build-backend = 'maturin'
