[build-system]
build-backend = "hatchling.build"
requires = [ "hatch-vcs", "hatchling" ]

[project]
name = "gvrender"
description = "Renders GraphViz graphs to Matplotlib surfaces."
readme = "README.rst"
license = "GPL-3.0-or-later"
authors = [ { name = "Phil A.", email = "flying-sheep@web.de" } ]
requires-python = ">=3.9"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dynamic = [ "version" ]
dependencies = [
  "matplotlib",
  "numpy>=1.20",                              # numpy.typing
  "pygraphviz",
  "typing-extensions; python_version<'3.12'",
  "xdot-rs>=0.2.3",
]
# Documentation = 'https://gvrender.readthedocs.org/en/latest/'
urls.Source = "https://github.com/flying-sheep/gvrender"

[dependency-groups]
test = [ "pytest", "pytest-mpl" ]

[tool.hatch]
version.source = "vcs"
build.hooks.vcs.version-file = "src/gvrender/_version.py"
envs.hatch-test.dependency-groups = [ "test" ]
envs.hatch-test.extra-scripts.baseline = "pytest --mpl-generate-path=tests/baseline"

[tool.ruff]
line-length = 100
src = [ "src", "tests" ]
format.quote-style = "single"
lint.select = [
  "E",    # Pycodestyle errors
  "F",    # Pyflakes
  "I001", # isort
  "UP",   # pyupgrade
  "W",    # Pycodestyle warnings
]
lint.isort.known-first-party = [ "gvrender" ]
lint.isort.required-imports = [ "from __future__ import annotations" ]

[tool.mypy]
mypy_path = "src:typings"
explicit_package_bases = true
strict = true

[tool.pyright]
include = [ "src" ]

[tool.pytest]
addopts = [ "--import-mode=importlib", "--mpl" ]
filterwarnings = [
  "error",
  'ignore:datetime.datetime.utcfromtimestamp\(\) is deprecated',
]
strict = true
