# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PIP_ROOT_USER_ACTION: ignore

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: pip
        cache-dependency-path: '**/pyproject.toml'
    - uses: ts-graphviz/setup-graphviz@v1
    - name: Install dependencies
      run: |
        pip install --upgrade pip wheel
        pip install --debug '.[test]'
    - uses: jakebailey/pyright-action@v1
      with:
        version: 1.1.311
    - name: Tests
      id: tests
      run: pytest -v --color=yes --mpl-results-path=tests/results --mpl-generate-summary=html
    - if: failure() && steps.tests.outcome == 'failure'
      uses: actions/upload-artifact@v3
      with:
        name: mpl-results-${{ github.ref_name }}-${{ github.sha }}
        path: tests/results/
