# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: pip
        cache-dependency-path: '**/pyproject.toml'
    - name: Install dependencies
      run: |
        pip install --upgrade pip wheel
        pip install --debug '.[test]'
    - uses: jakebailey/pyright-action@v1
      with:
        version: 1.1.244
    - name: Tests
      run: pytest -v --color=yes
